services:
  redcurrant-platform:
    mem_limit: 1024M
    image: redcurrant-platform
    container_name: redcurrant-platform
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080/tcp
