name: redcurrant-platform
replicas: 1
containerPort: 15511
image: luluorgacr.azurecr.io/cbaas-redcurrant-platform
tag: dev-snapshot
memoryRequest: 256Mi
cpuRequest: 10m
memoryLimit: 1024Mi
cpuLimit: 1000m
namespace: cbaas-dev-blu
nodeSelectorLabel: "luluorg"
livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 10
  failureThreshold: 5
readinessProbe:
  initialDelaySeconds: 100
  periodSeconds: 5
  failureThreshold: 10
tolerations: 'true'
ENV:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: DB_URL
    value: 'jdbc:mysql://postgres-db.cbaas-dev-blk.svc.cluster.local:3306'
  - name: DB_USERNAME
    value: service_user
  - name: DB_PASSWORD
    value: 47h9c6Pz4!ts
  - name: RC_APP_CONTEXT
    value: /redcurrant-platform/
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "*"
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,address=52211,server=y,suspend=n
