name: redcurrant-platform
replicas: 1
containerPort: 15511
image: luluorgacr.azurecr.io/cbaas-redcurrant-platform 
tag: stg-snapshot
memoryRequest: 256Mi
cpuRequest: 10m
memoryLimit: 1024Mi
cpuLimit: 1000m
namespace: cbaas-stg-blu
nodeSelectorLabel: "luluorg"
livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 10
  failureThreshold: 5
readinessProbe:
  initialDelaySeconds: 100
  periodSeconds: 5
  failureThreshold: 10
ENV:
  - name: SPRING_PROFILES_ACTIVE
    value: staging
  - name: RC_IDM_URL
    value: http://idm.cbaas-stg-wht.svc.cluster.local:13250
  - name: RC_SWAGGER_IDM_URL
    value: https://stg.digitnine.com/idm/oauth/token
  - name: DB_URL
    value: 'jdbc:mysql://mysql-db.cbaas-stg-blk.svc.cluster.local:3306'
  - name: DB_USERNAME
    value: service_user
  - name: DB_PASSWORD
    value: 47h9c6Pz4!ts
  - name: RC_APP_CONTEXT
    value: /redcurrant-platform/
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "*"
  - name: ELASTIC_APM_ENVIRONMENT
    value: stg
  - name: ELASTIC_APM_SERVER_URL
    value: http://apm-server.cbaas-stg-blk.svc.cluster.local:8200
