name: reports
replicas: 1
containerPort: 12211
image: luluorgacr.azurecr.io/cbaas-blu-reports
tag: dev-snapshot
memoryRequest: 256Mi
cpuRequest: 10m
memoryLimit: 1024Mi
cpuLimit: 1000m
namespace: cbaas-dev-blu
nodeSelectorLabel: "luluorg"
livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 10
  failureThreshold: 5
readinessProbe:
  initialDelaySeconds: 100
  periodSeconds: 5
  failureThreshold: 10
tolerations: 'true'
ENV:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: D9_IDM_URL
    value: http://idm.cbaas-dev-wht.svc.cluster.local:13250
  - name: BLU_REFERENCE_DATA_URL
    value: http://referencedata.cbaas-dev-blu.svc.cluster.local:12050
  - name: D9_SWAGGER_IDM_URL
    value: https://dev.digitnine.com/idm/oauth/token
  - name: DB_URL
    value: 'jdbc:postgresql://postgres-db.cbaas-dev-blk.svc.cluster.local:5432'
  - name: DB_USERNAME
    value: service_user
  - name: DB_PASSWORD
    value: 47h9c6Pz4!ts
  - name: D9_APP_CONTEXT
    value: /reports/
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "*"
  - name: ELASTIC_APM_ENVIRONMENT
    value: dev
  - name: ELASTIC_APM_SERVER_URL
    value: http://apm-server.cbaas-dev-blk.svc.cluster.local:8200
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,address=52211,server=y,suspend=n
#  - name: KAFKA_SERVER_URL
#    value: confluent-kafka-dev-op.digitnine.com:9092
